Define Overloads methods in WebGL2RenderingContext
Fix the following errors:
.../starfish_generated/binding/generated/WebGL2RenderingContextBinding.cpp:7815:18: error: request for member ‘bufferData’ is ambiguous
 7815 |     originalObj->bufferData(value0, value1, value2, value3, value4);
      |                  ^~~~~~~~~~
...

TODO: Make WebGL2RenderingContext base on WebGLRenderingContextBase
instead of WebGL2RenderingContext.